version: "3.3"

services:

  nginx:
    image: nginx:latest
    container_name: cache-server
    ports:
      - "773:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./ssl:/ssl
    networks:
      - any-3-network

networks:
  any-3-network:
    name: dockerfiles_default
    external: true
