version: "3.8"
services:

  nginx:
    image: nginx:latest
    container_name: drupal-nginx
    ports:
      - "54444:80"
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ./configs/fastcgi-params.conf:/etc/nginx/conf.d/fastcgi-params.conf
      - ./configs/response-debug-headers.conf:/etc/nginx/conf.d/response-debug-headers.conf
      - ./wwwroot:/wwwroot:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php

  php:
    build:
      context: ./server/php
    container_name: drupal-php
    volumes:
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ./wwwroot:/wwwroot
      - ./logs/php:/var/log/php
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: drupal-database
    ports:
      - "8806:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=blog
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
