[package]
name = "criterion_benchmarking"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "zeros_matrix_benchmark"
harness = false

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
