# frozen_string_literal: true

require 'rubocop/rake_task'

task default: %w[lint test]

RuboCop::RakeTask.new(:lint) do |task|
  task.patterns = ['lib/**/*.rb', 'test/**/*.rb']
  task.fail_on_error = true
  task.requires << 'rubocop-minitest'
  task.requires << 'rubocop-rake'
end

task :run do
  ruby 'main.rb'
end

task :test do
  ruby 'test/cool_program_test.rb'
end
